### ISSUE TITLE
Connect "several threads support" to frontend

### ISSUE THREAD

**Issue by slry** [InnoSWP/InnoSCS#26]
We need to discuss how to connect support of several threads to frontend part.

**Comment by macoyshev** [comment]
Support of several connections is already implemented, the frontend just need to send a new post request to create a new thread, to make app stateless(without storing information of a user on backend), we can store WS identificators on frontend part(LocalStorage or JS object)

**Comment by macoyshev** [comment]
@slry, can you create a new branch and push there you results to see what is done ?
